### ISSUE TITLE
Implement vanilla ICP

### ISSUE THREAD

**Issue by icemiliang** [shuangchenpro/ot_study#2]
Implement the original ICP algorithm

- [x] Nearest neighbor search
- [x] Fit transformation
- [x] Wrapper (an outer function to alternatively search for nearest neighbors and fit a transformation)
- [x] Decorate (comments, error handler, timer, etc.)

**Comment by shuangchenpro** [comment]
代码跑通了， 还能显示匹配错点个数，但实验了一下感觉这个意义不大，一共34000+个点，现在这个测试，迭代113次，全都匹配上，迭代110次，错匹配7700+，迭代100次，错匹配32000+，感觉显示错点个数没啥用。

tips：
1.  icp 输入是两个点云，但输出可能有 R、t、运行时间、迭代次数、distances等。 所以，需要把icp改成类吗？
2. helpfunc 有些函数需要改一下，比如 调用draw的时候可以直接设置draw 的 dotsize
3. 也许以后可以尝试动画显示 icp过程，也许
4. ot 是不是 可能要处理2个以上点云，需要把icp的结构改改为这个做准备吗？

**Comment by icemiliang** [comment]
> icp 输入是两个点云，但输出可能有 R、t、运行时间、迭代次数、distances等。 所以，需要把icp改成类吗？

That is not necessary for now because we will only use a few functions from here for future work.

**Comment by icemiliang** [comment]
> 也许以后可以尝试动画显示 icp过程，也许

Created a separate issue for animation. #6

**Comment by icemiliang** [comment]
> ot 是不是 可能要处理2个以上点云，需要把icp的结构改改为这个做准备吗？

It is fine for now. When we work on multiple point clouds, each time we still compute pair-wise ICP.

**Comment by shuangchenpro** [comment]
cloud points in ply file could not be registered. @icemiliang

**Comment by icemiliang** [comment]
> cloud points in ply file could not be registered.
Have you solved the issue? It works fine in the current version.

**Comment by shuangchenpro** [comment]
> > cloud points in ply file could not be registered.
> 
> Have you solved the issue? It works fine in the current version.

I try to resolve, but I found that is because of icp. No matter obj. or ply., they all could not be registered in some angles. I have said about this problem in comment about pulling request, but forget to delete this comment. That is a misunderstanding. 

By the way, I guess the test edge angle is 70 degrees.

**Comment by icemiliang** [comment]
Done. #7
